config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#public'
  match 'public_recipes' => 'public_recipes#index', as: :public_recipes, via: :get

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :recipes, except: :update do
    resources :recipe_foods
  end
  resources :foods, except: :update

  resources :inventories do
    resources :inventory_foods
  end

  resource :shopping_lists, only: [:index]
  get 'recipes/:recipe_id/generate_shopping_list', to: 'shopping_lists#new'
  post 'recipes/:recipe_id/generate_shopping_list', to: 'shopping_lists#create'
  get 'shopping_list/:recipe_id/:inventory_id', to: 'shopping_lists#index'
  post 'recipes/new', to: 'recipes#create'
  post 'recipes/:recipe_id/recipe_food/new', to: 'recipe_foods#new'
  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food
  has_many :inventory_foods, dependent: :delete_all
  has_many :inventories, through: :inventory_foods, dependent: :destroy
  has_many :recipe_foods, dependent: :delete_all

  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :inventory_foods, foreign_key: 'inventory_id', dependent: :destroy
  has_many :foods, through: :inventory_foods, dependent: :destroy
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 200 }

  def related_inventory_foods
    inventory_foods.includes(:food)
  end
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory, foreign_key: 'inventory_id'
  belongs_to :food, foreign_key: 'food_id'
  belongs_to :user

  validates :quantity, numericality: { greater_than: 0 }, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :inventories
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods
  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      flash[:success] = 'New inventory has been created !!'
      redirect_to foods_path
    else
      flash['alert'] = 'Inventory could not created !!'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:success] = 'Inventory has been deleted successfully'
    redirect_to foods_path
  end

  private

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit!
  end
end

app/controllers/ineventory_controller.rb
class InventoriesController < ApplicationController
  def index
    @user = current_user
    @inventories = @user.inventories
  end

  def show
    @user = current_user
    @inventory = @user.inventories.find(params[:id])
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user_id = current_user.id

    render :new unless @inventory.save

    redirect_to inventories_path
  end

  def destroy
    @inventory = Inventory.find_by(id: params[:id])

    if @inventory.destroy
      flash[:notice] = 'Inventory deleted!'
    else
      flash[:alert] = 'Error! Please try again later.'
    end
    redirect_to inventories_path
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @user = current_user
    @inventories = @user.inventories
  end

  def show
    @user = current_user
    @inventory = @user.inventories.find(params[:id])
    @foods = @inventory.inventory_foods.includes(:food)
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user_id = current_user.id

    render :new unless @inventory.save

    redirect_to inventories_path
  end

  def destroy
    @inventory = Inventory.find_by(id: params[:id])

    if @inventory.destroy
      flash[:notice] = 'Inventory deleted!'
    else
      flash[:alert] = 'Error! Please try again later.'
    end
    redirect_to inventories_path
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
  before_action :set_inventory

  def new
    @inventory_food = InventoryFood.new
    @foods = Food.all
  end

  def create
    @inventory_food = InventoryFood.new(inventory_food_params)
    @inventory_food.inventory_id = @inventory.id

    respond_to do |format|
      if @inventory_food.save
        format.html { redirect_to inventory_path(@inventory.id), notice: 'Inventory food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory_food = InventoryFood.find(params[:id])
    @inventory_food.destroy

    respond_to do |format|
      format.html { redirect_to inventory_path(@inventory.id), notice: 'Inventory food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_inventory
    @inventory = Inventory.find(params[:inventory_id])
  end

  def inventory_food_params
    params.require(:inventory_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    return if current_user.nil?

    @current_user = current_user
    @recipes = @current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
    @inventories = Inventory.all
  end

  def public
    @recipes = Recipe.where(public: true)
  end

  def new
    @user = current_user

    recipe = Recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: } }
    end
  end

  def create
    @user = current_user
    @recipe = Recipe.new(recipe_params)
    @recipe.user = @user
    if @recipe.save
      flash[:notice] = 'recipe was saved successfully'
      redirect_to recipes_path
    else
      flash.now[:notice] = 'Error:recipe could not be saved'
      render :new, locals: { recipe: @recipe }
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    user = current_user
    recipe.destroy
    if user.save
      flash[:notice] = 'Recipe was successfully deleted.'
      redirect_to recipes_path
    else
      render :new, alert: 'Error can not delete deleting the recipe'
    end
  end

  private

  def recipe_params
    params.permit(:name, :description, :cooking_time, :preparation_time, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/turbo_devise_user_helper.rb
module TurboDeviseUserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inventory_foods/_form.html.erb
<%= form_with model: inventory_food, url: inventory_inventory_foods_path(@inventory), method: :post, class:"inventory-form" do |form| %>
  <% if inventory_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory_food.errors.count, "error") %> prohibited this inventory_food from being saved:</h2>

      <ul>
        <% inventory_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @foods.length > 0 %>
      <%= form.label :quantity, class:"inventory-label" %>
      <%= form.number_field :quantity,:required => true , class:"inventory-input"%>
      <%= form.label "Select Food", class:"inventory-label" %>
      <%= form.select :food_id, @foods.map { |food| [food.name, food.id] } %>
      <%= form.submit "Add Food To Inventory", class:"inventory-submit-btn"%>
  <% else %>
    <h3 class="inventory-empty-data">No Food in Food store.</h3>
  <% end %>
<% end %>

app/views/inventory_foods/new.html.erb
<div class="inventory-form-cont">
  <h1>New Inventory Food</h1>
  <%= render "form", inventory_food: @inventory_food %><br/>
  <%= link_to "You can add new food in food store here", new_food_path, class:"inventory-new"%>
</div>

app/views/inventory_foods/show.html.erb
<%= form_with model: inventory_food, url: inventory_inventory_foods_path(@inventory), method: :post, class:"inventory-form" do |form| %>
  <% if inventory_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory_food.errors.count, "error") %> prohibited this inventory_food from being saved:</h2>

      <ul>
        <% inventory_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @foods.length > 0 %>
      <%= form.label :quantity, class:"inventory-label" %>
      <%= form.number_field :quantity,:required => true , class:"inventory-input"%>
      <%= form.label "Select Food", class:"inventory-label" %>
      <%= form.select :food_id, @foods.map { |food| [food.name, food.id] } %>
      <%= form.submit "Add Food To Inventory", class:"inventory-submit-btn"%>
  <% else %>
    <h3 class="inventory-empty-data">No Food in Food store.</h3>
  <% end %>
<% end %>