config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#public'
  match 'public_recipes' => 'public_recipes#index', as: :public_recipes, via: :get

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :recipes, except: :update do
    resources :recipe_foods
  end
  resources :foods, except: :update

  resources :inventories do
    resources :inventory_foods
  end

  resource :shopping_lists, only: [:index]
  get 'recipes/:recipe_id/generate_shopping_list', to: 'shopping_lists#new'
  post 'recipes/:recipe_id/generate_shopping_list', to: 'shopping_lists#create'
  get 'shopping_list/:recipe_id/:inventory_id', to: 'shopping_lists#index'
  post 'recipes/new', to: 'recipes#create'
  post 'recipes/:recipe_id/recipe_food/new', to: 'recipe_foods#new'
  # Defines the root path route ("/")
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :inventory_foods, foreign_key: 'inventory_id', dependent: :destroy
  has_many :foods, through: :inventory_foods, dependent: :destroy
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 200 }

  def related_inventory_foods
    inventory_foods.includes(:food)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @user = current_user
    @inventories = @user.inventories
  end

  def show
    @user = current_user
    @inventory = @user.inventories.find(params[:id])
    @foods = @inventory.inventory_foods.includes(:food)
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user_id = current_user.id

    render :new unless @inventory.save

    redirect_to inventories_path
  end

  def destroy
    @inventory = Inventory.find_by(id: params[:id])

    if @inventory.destroy
      flash[:notice] = 'Inventory deleted!'
    else
      flash[:alert] = 'Error! Please try again later.'
    end
    redirect_to inventories_path
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory, class:"container w-full p-4 b-2") do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name, class:"form-label" %>
  <%= form.text_field :name,:required => true , class: "form-control mb-2" %>
  <%= form.label :description, class:"form-label" %>
  <%= form.text_area :description, placeholder: 'Write your description...', class: "form-control mb-2" %>
  <%= form.submit "Create Inventory", class:"btn btn-primary" %>
<% end %>

app/views/inventories/index.html.erb
<section class="inventory-section">
  <% if @inventories.any? %>
      <% @inventories.each do |inventory| %>
        <div class="inventory-container">
          <div>
            <a href="<%= inventory_path(inventory) %>"><h2><%= inventory.name %></h2></a>
            <%= button_to "REMOVE", inventory,class:"btn btn-danger mt-4", method: :delete %>
          </div>
          <div class="description">
            <p><%= inventory.description%></p>
          </div>
        </div>
      <% end %>
  <% else %>
    <h3 class="inventory-empty-data">No Inventories!</h3>
  <% end %>
  <%= link_to "Create new inventory", new_inventory_path, class:"btn btn-primary mt-2" %>
</section>

app/views/inventories/new.html.erb
<div class="inventory-form-cont">
  <h1 class="mt-3">New inventory</h1>
  <%= render "form", inventory: @inventory %><br/>
  <%= link_to "Back to inventories", inventories_path, class:"btn btn-secondary" %>
</div>

app/views/inventories/show.htlm.erb
<section class="inventory-section h-screen">
  <div class = "inventory-header">
    <h1 class="text-grayDark mt-8"><%= @inventory.name%></h1>
    <div class="container add-food-btn-container w-full flex justify-end mb-4 p-0">
      <% if @inventory.user == current_user %>
        <%= link_to "Add Food", new_inventory_inventory_food_path(@inventory.id), class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <% if @inventory.user == current_user %>
    <% if @inventory.related_inventory_foods.any? %>
      <table class="table table-striped table-hover table-bordered">
        <thead class="table-dark">
          <tr>
            <th scope="col">Food</th>
            <th scope="col">Quantity</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @inventory.related_inventory_foods.each do |inventory_food| %>
            <% if inventory_food.food %>
              <tr>
                <td scope="row"><%= inventory_food.food.name %></td>
                <td scope="row"><%= inventory_food.quantity %><%= inventory_food.food.measurement_unit %></td>
                <td scope="row"> <%= button_to "Remove", inventory_inventory_food_path(inventory_food.inventory.id, inventory_food), method: :delete , class:"btn btn-secondary"%></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h3 class="inventory-empty-data">No Food added to this Inventory</h3>
    <% end %>
  <% end %>
</section>

app/views/inventories/show.html.erb
<section class="inventory-section h-screen">
  <div class = "inventory-header">
    <h1 class="text-grayDark mt-8"><%= @inventory.name%></h1>
    <div class="container add-food-btn-container w-full flex justify-end mb-4 p-0">
      <% if @inventory.user == current_user %>
        <%= link_to "Add Food", new_inventory_path(@inventory.id), class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <% if @inventory.user == current_user %>
    <% if @inventory.related_inventory_foods.any? %>
      <table class="table table-striped table-hover table-bordered">
        <thead class="table-dark">
          <tr>
            <th scope="col">Food</th>
            <th scope="col">Quantity</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @inventory.related_inventory_foods.each do |inventory_food| %>
            <% if inventory_food.food %>
              <tr>
                <td scope="row"><%= inventory_food.food.name %></td>
                <td scope="row"><%= inventory_food.quantity %><%= inventory_food.food.measurement_unit %></td>
                <td scope="row"> <%= button_to "Remove", inventory_inventory_food_path(inventory_food.inventory.id, inventory_food), method: :delete , class:"btn btn-secondary"%></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h3 class="inventory-empty-data">No Food added to this Inventory</h3>
    <% end %>
  <% end %>
</section>