config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#public'
  match 'public_recipes' => 'public_recipes#index', as: :public_recipes, via: :get

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :recipes, except: :update do
    resources :recipe_foods
  end
  resources :foods, except: :update

  resources :inventories do
    resources :inventory_foods
  end

  resource :shopping_lists, only: [:index]
  get 'recipes/:recipe_id/generate_shopping_list', to: 'shopping_lists#new'
  post 'recipes/:recipe_id/generate_shopping_list', to: 'shopping_lists#create'
  get 'shopping_list/:recipe_id/:inventory_id', to: 'shopping_lists#index'
  post 'recipes/new', to: 'recipes#create'
  post 'recipes/:recipe_id/recipe_food/new', to: 'recipe_foods#new'
  # Defines the root path route ("/")
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    return if current_user.nil?

    @current_user = current_user
    @recipes = @current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
    @inventories = Inventory.all
  end

  def public
    @recipes = Recipe.where(public: true)
  end

  def new
    @user = current_user

    recipe = Recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: } }
    end
  end

  def create
    @user = current_user
    @recipe = Recipe.new(recipe_params)
    @recipe.user = @user
    if @recipe.save
      flash[:notice] = 'recipe was saved successfully'
      redirect_to recipes_path
    else
      flash.now[:notice] = 'Error:recipe could not be saved'
      render :new, locals: { recipe: @recipe }
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    user = current_user
    recipe.destroy
    if user.save
      flash[:notice] = 'Recipe was successfully deleted.'
      redirect_to recipes_path
    else
      render :new, alert: 'Error can not delete deleting the recipe'
    end
  end

  private

  def recipe_params
    params.permit(:name, :description, :cooking_time, :preparation_time, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<%if user_signed_in?%>
<%= render :partial => "shared/recipelist", :recipes => :recipes %>
<%else%>
  <h2>Sign in to see your recipes</h2>
<%end%>

app/views/recipes/new.html.erb
<div class="card p-2 bg-light">
  <h1>New Recipe</h1>
  <%= form_with model: @recipe, class: 'w-100 d-flex flex-column'  do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, class:'form-control', placeholder: 'name',:required => true ,autofocus: true %>
    <%= form.label :preparation_time %>
    <%= form.text_field :preparation_time, class:'form-control-sm w-25', placeholder: 'preparation time' %>
    <%= form.label :cooking_time %>
    <%= form.text_field :cooking_time, class:'form-control-sm w-25', placeholder: 'cooking time' %>
    <%= form.label :description %>
    <%= form.text_field :description, class:'form-control', placeholder: 'description...' %>
    <%= form.label :public %>
  <%= form.check_box :public, class:'form-check-input mb-2 ms-2', placeholder: 'Is this recipe public'%>

  <%= form.submit "Create Recipe", class:"btn btn-success" %>
  
<% end %>
</div>
<%= link_to "<-- Go Back ", :back, class:'btn btn-secondary w-25 mt-2' %>

app/views/recipes/public.html.erb
<h1> This is the the list of all public recipes</h1>
<%= render :partial => "shared/recipelist", :recipes => :recipes %>

app/views/recipes/show.html.erb
<div class=' border-bottom p-3'>
  <h1 class='text-center'> <%= @recipe.name %></h1>
  <div class= 'd-flex justify-content-between'>
  <div>preparation time: <%= @recipe.preparation_time%></div>
  <span><%= @recipe.public %></span>
  </div>

  <div>coooking time: <%= @recipe.cooking_time %></div>
  <div>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
     Generate Shopping list
    </button>

    <!-- Modal -->
    <div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content "  style="height: 400px;">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <h2> Choose an inventory to use </h2>
            <ul>
              <% @inventories.each do |inventory| %>
                  <li><%=inventory.name%></li>
                  <%= link_to 'generate' , new_inventory_inventory_food_path(inventory.id) %>
              <%end%>
            </ul>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

          </div>
        </div>
      </div>
    </div>

    <% if @recipe.user == current_user %>
      <%= link_to 'Add ingredients', new_recipe_recipe_food_path(@recipe), class: 'btn btn-outline-info' %>
    <%end%>
  </div>
</div>
<table class="table table-hover border  mt-2">
  <thead class=' text-secondary'>
    <tr class='bg-light'>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @recipe_foods.each do |recipe_food| %>
    <tr>
      <td><%=recipe_food.food.name%></td>
      <td><%=recipe_food.food.measurement_unit%></td>
      <td><%=recipe_food.food.price%></td>
      <td>
      <div class= 'btn-group'>
      <% if @recipe.user == current_user %>
      <%= button_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food), class: 'btn btn-outline-dark' %>
      <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: 'btn btn-outline-danger' %>
      <%end%>

      </td>
    </tr>
  <%end%>
  </tbody>
</table>

<%= link_to "<-- Go Back ", :back, class:'btn btn-secondary w-25 mt-2' %>