config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#public'
  match 'public_recipes' => 'public_recipes#index', as: :public_recipes, via: :get

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :recipes, except: :update do
    resources :recipe_foods
  end
  resources :foods, except: :update

  resources :inventories do
    resources :inventory_foods
  end

  resource :shopping_lists, only: [:index]
  get 'recipes/:recipe_id/generate_shopping_list', to: 'shopping_lists#new'
  post 'recipes/:recipe_id/generate_shopping_list', to: 'shopping_lists#create'
  get 'shopping_list/:recipe_id/:inventory_id', to: 'shopping_lists#index'
  post 'recipes/new', to: 'recipes#create'
  post 'recipes/:recipe_id/recipe_food/new', to: 'recipe_foods#new'
  # Defines the root path route ("/")
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food
  has_many :inventory_foods, dependent: :delete_all
  has_many :inventories, through: :inventory_foods, dependent: :destroy
  has_many :recipe_foods, dependent: :delete_all

  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods
  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      flash[:success] = 'New inventory has been created !!'
      redirect_to foods_path
    else
      flash['alert'] = 'Inventory could not created !!'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:success] = 'Inventory has been deleted successfully'
    redirect_to foods_path
  end

  private

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit!
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<div class="container h-screen">
<h1 class="text-grayDark mt-8">List of foods</h1>
    <div class="container w-full flex justify-end mb-4 p-0">
      <%= link_to "Add food", new_food_path, class:"btn btn-primary" %>
    </div>
    <table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @foods.each do |food| %>
    <tr>
      <th scope="row"><%= food.name %></th>
      <td><%= food.measurement_unit %></td>
      <td>$<%= food.price %></td>
      <td><%= button_to "Delete", food_path(food.id), method: :delete, class: "btn text-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/foods/new.html.erb
<div class="container w-full p-4 b-2">
    <h2 class="text mb-4">Add new food</h2>
    <%= form_with model: @food, url: foods_path,  local: true, data: {turbo:false} do |f| %>
        <div class="mb-3">
            <%= f.label :name, class: "form-label" %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= f.label :measurement_unit, class: "form-label" %>
            <%= f.text_field :measurement_unit, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= f.label :price, class: "form-label" %>
            <%= f.number_field :price, class: "form-control" %>
        </div>
        <%= f.submit class: "btn btn-primary" %>
    <% end %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>
  <%= button_to "Destroy this food", @food, method: :delete %>
</div>